### PR TITLE
fix(mulligan): turn mulliganActive true on MULLIGAN_STATE INPUT

### PR DESCRIPTION
**Pull request by Hoishin**

### CODE REVIEW

**Comment by rikumiyao** [comment]
Can you check that this works for spectated games.

**Comment by Hoishin** [comment]
It only works for spectated games

**Comment by rikumiyao** [comment]
It would make sense to have test cases that have specated games since I didnt include them myself. I will leave that to your discretion

**Comment by Hoishin** [comment]
Will be adding tests later

**Pull request merged**
